# Generated by Django 3.0.1 on 2019-12-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeedbackApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('feedbackId', models.IntegerField(default=0)),
                ('avg_rating', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedbackApp.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedbackApp.Department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedbackApp.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedbackApp.Teacher')),
            ],
        ),
    ]
