# Generated by Django 3.0.1 on 2019-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedbackApp', '0004_remove_feedback_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='feedback_data',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
