# Generated by Django 3.0.1 on 2020-01-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedbackApp', '0005_auto_20191230_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_data',
            name='value_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_10',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_11',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_12',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_13',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_14',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_8',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback_data',
            name='value_9',
            field=models.FloatField(default=0.0),
        ),
    ]
